server:
  port: 8088
spring:
  # mysql
  datasource:
    url: jdbc:mysql://152.136.56.27:3306/cloud_order?useSSL=false
    username: root
    password: ysbb284650
    driver-class-name: com.mysql.jdbc.Driver
  # Redis
  redis:
    host: 152.136.56.27
    port: 6379
    timeout: 5000 # 连接超时时间（单位：毫秒）
    jedis:
      pool:
        max-active: 10
    password: 123456
  application:
    name: payment-service
# rabbitmq
  rabbitmq:
    host: 152.136.56.27
    port: 5672
    username: yu7
    password: 284650
    virtual-host: /
#Actuator
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    #Eureka客户端从Eureka服务器获取注册表信息的时间间隔，这里配置为10秒
    #每次获取全量注册信息
    disable-delta: false
    #服务消费者从注册中心拉取服务列表
    fetch-registry: true
# 日志级别
logging:
  level:
    com.yu7: debug

mybatis:
  type-aliases-package: yu7.order.pojo
  configuration:
    map-underscore-to-camel-case: true

#Ribbon同步缓存的时间
eureka-server:
            url: http://127.0.0.1:10086/eureka/apps/
            appName: user-service

