#spring:
#  datasource:
#    url: jdbc:mysql://152.136.56.27:3306/cloud_order?useSSL=false
#    username: root
#    password: 284650
#    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: orderservice
##  cloud:
##    nacos:
##      server-addr: nacos:8848 # nacos服务地址
##      discovery:
##        namespace: 4d6ce343-9e1b-44df-a90f-2cf2b6b3d177 # dev环境
##        ephemeral: false # 是否是临时实例
#  pattern:
#    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
#userservice:
#  ribbon:
#    #NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
#ribbon:
#  eager-load:
#    enabled: true # 开启饥饿加载
#    clients: # 指定饥饿加载的服务名称
#      - userservice
#feign:
#  httpclient:
#    enabled: true # 支持HttpClient的开关
#    max-connections: 200 # 最大连接数
#    max-connections-per-route: 50 # 单个路径的最大连接数
server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://152.136.56.27:3306/cloud_order?useSSL=false
    username: root
    password: ysbb284650
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: payment-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
      #  Eureka 客户端从 Eureka 服务器获取注册表信息的时间间隔，这里配置为 5 秒
      registryFetchIntervalSeconds: 5
  server:
  #是否使用只读缓存
#    use-read-only-response-cache: false

# 修改心跳时间
#  server:
#    eviction-interval-timer-in-ms: 100000
# 日志级别
logging:
  level:
    com.yu7: debug

mybatis:
  type-aliases-package: yu7.order.pojo
  configuration:
    map-underscore-to-camel-case: true

    #Ribbon同步缓存的时间
eureka-server:
            url: http://127.0.0.1:10086/eureka/apps/
            appName: user-service

