server:
  port: 8081
spring:
#mysql
  datasource:
    url: jdbc:mysql://152.136.56.27:3306/cloud_user?useSSL=false
    username: root
    password: ysbb284650
    driver-class-name: com.mysql.jdbc.Driver
#Redis
  redis:
    host: 152.136.56.27
    port: 6379
    password: 123456
    timeout: 5000 # 连接超时时间（单位：毫秒）
    jedis:
      pool:
        max-active: 10
#服务名称
  application:
           name: user-service
#rabbitmq
  rabbitmq:
    host: 152.136.56.27
    port: 5672
    username: yu7
    password: 284650
    virtual-host: /
#Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#Eureka客户端从Eureka服务器获取注册表信息的时间间隔，这里配置为 10 秒
    registry-fetch-interval-seconds: 10
    #每次获取全量注册信息
    disable-delta: false
    #服务消费者从注册中心拉取服务列表
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 1 #Eureka客户端多长时间发送心跳给Eureka服务端，这个代表他自己是否存活，默认时间为30S
    lease-expiration-duration-in-seconds: 3 #Eureka服务器在接受到实例的最后一次发出的心跳后需要多长时间才能
mybatis:
  type-aliases-package: com.yu7.user.pojo #该包下别名注册到mybatis
  configuration:
    map-underscore-to-camel-case: true #下划线转驼峰映射
logging:
  level:
    com.yu7: debug
#Actuator
#management:
#  endpoint:
#    shutdown:
#      enabled: true #启用 shutdown 端点，默认是未启用的
#  endpoints:
#      web:
#        exposure:
#          include: health,info,shutdown #对外公开 health,info,shutdown 端点，默认只会公开前两个
#Actuator
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
# 配置
eureka-server:
          ipAddress: 127.0.0.1
          appName: user-service
DIY_QUEUE:
    VALUE: USER-QUEUE
DIY_EXCHANGE:
    VALUE: USER-TOPIC





