#spring:
#  datasource:
#    url: jdbc:mysql://152.136.56.27:3306/cloud_user?useSSL=false
#    username: root
#    password: 284650
#    driver-class-name: com.mysql.jdbc.Driver
#  shardingsphere:
#    sharding:
#      default-database-strategy:
#      tables:
##      discovery:
##        cluster-name: HZ
#logging:
#  level:
#    cn.itcast: debug
#  pattern:
#    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
#pattern:
#  name: 本地环境local
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://152.136.56.27:3306/cloud_user?useSSL=false
    username: root
    password: ysbb284650
    driver-class-name: com.mysql.jdbc.Driver
  application:
           name: user-service # 服务名称
# Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
      #  Eureka 客户端从 Eureka 服务器获取注册表信息的时间间隔，这里配置为 5 秒
      registryFetchIntervalSeconds: 1
#    registry-fetch-interval-seconds: 180
  #    fetch-registry: false  #是否从Eureka服务器获取注册表信息
 #  修改心跳时间
mybatis:
  type-aliases-package: com.yu7.user.pojo #该包下别名注册到mybatis
  configuration:
    map-underscore-to-camel-case: true #下划线转驼峰映射
logging:
  level:
    com.yu7: debug
# Actuator
management:
  endpoint:
    shutdown:
      enabled: true #启用 shutdown 端点，默认是未启用的
  endpoints:
      web:
        exposure:
          include: health,info,shutdown #对外公开 health,info,shutdown 端点，默认只会公开前两个
# 配置
eureka-server:
          ipAddress: 127.0.0.1
          appName: user-service



