server:
  port: 10086 # 服务端口
spring:
  application:
    name: eurekaserver # eureka的服务名称
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: true
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
#关闭Eureka的自我保护
  server:
    enable-self-preservation: true
    # 不使用只读缓存
#    use-read-only-response-cache: false
    UseReadOnlyResponseCache: true
  # 修改心跳时间
#  server:
#    eviction-interval-timer-in-ms: 10000
# 日志级别
logging:
  level:
    com.yu7: debug
# 配置属性
eureka-server:
          name: 127.0.0.1:10086

