server:
  port: 10086 # 服务端口
spring:
  cloud:
   loadbalancer:
        ribbon:
          enabled: false
  application:
    name: eurekaserver # eureka的服务名称
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    #清理失效实例的时间间隔为3.2秒
    eviction-interval-timer-in-ms: 3000
    response-cache-update-interval-ms: 3000
    response-cache-auto-expiration-in-seconds: 180
    #自我保护，防止注册中心和网络之间出现问题
    enable-self-preservation: false
    #开启三级缓存
    useReadOnlyResponseCache: false
#Actuator
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
# 日志级别
logging:
  level:
    com.yu7: debug
# 配置属性
eureka-server:
          name: 127.0.0.1:10086

